name: Publish Linux Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -f gradefx javafx:jlink
      env:
        GITHUB_TOKEN: ${{ github.token }}
        
    - name: Create DEB with Maven
      run: mvn -f gradefx jpackage:jpackage@linux-deb
      env:
        GITHUB_TOKEN: ${{ github.token }}
        
    - name: Create RPM with Maven
      run: mvn -f gradefx jpackage:jpackage@linux-rpm
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Make staging directory
      run: mkdir staging

    - name: Copy to staging
      run: |
        cp -r gradefx/target/dist/* staging
        
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linux
        path: staging
        
    - name: Zip files for release
      shell: pwsh
      run: |
        cd staging
        tar -czf linux-deb.tar.gz *.deb
        tar -czf linux-rpm.tar.gz *.rpm
        cd ..
        
    - name: Upload DEB to release
      uses: svenstaro/upload-release-action@2.11.2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: staging/linux-deb.tar.gz
        tag: ${{ github.ref }}
        overwrite: true
        
    - name: Upload DEB to release
      uses: svenstaro/upload-release-action@2.11.2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: staging/linux-rpm.tar.gz
        tag: ${{ github.ref }}
        overwrite: true
