# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -f gradefx javafx:jlink jpackage:jpackage
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Make staging directory
      run: mkdir staging

    - name: Copy jar to staging
      run: |
        cp -r gradefx/target/dist/* staging
        
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}
        path: staging
        
    - name: Zip files for Release
      shell: pwsh
      run: |
        cd staging
        if ($env:RUNNER_OS -eq "Windows") {
          7z a ${{ matrix.os }}.zip *
        }
        else {
          zip -r ${{ matrix.os }}.zip *
        }
        cd ..
        
    - name: Upload files to release
      uses: svenstaro/upload-release-action@2.11.2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: staging/${{ matrix.os }}.zip
        tag: ${{ github.ref }}
        overwrite: true
